import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Hero from "../components/Hero";

export default function Home() {
  const [users, setUsers] = useState();


  return (
    <div>
      <Head>
        <title>KO Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading={'KO Photography'} message={'I take pictures of people.'}/>

      <section className='h-screen bg-black'>
        
      </section>
    </div>
  );
}


ghana


