import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>KO Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hero></hero>
        {/* <div className='flex items-center justify-center h-screen mb-12 bg-fixed bg-center '>
          <h2>Heading</h2>
          <p>Message</p>
          <h3> Book</h3>
        </div> */}
      </div>
  );
}
